#!/bin/sh
set -eu

psql --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" \
  --set=ON_ERROR_STOP=1 \
  --set=app_password="$POSTGRES_APP_PASSWORD" <<'SQL'
CREATE ROLE crediai_app WITH LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS PASSWORD :'app_password';
GRANT CONNECT ON DATABASE crediai TO crediai_app;
GRANT USAGE ON SCHEMA public TO crediai_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO crediai_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO crediai_app;
ALTER DEFAULT PRIVILEGES FOR ROLE crediai_owner IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO crediai_app;
ALTER DEFAULT PRIVILEGES FOR ROLE crediai_owner IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO crediai_app;
SQL
